services:
        ipsec_exporter:
                #restart: unless-stopped
                build: .
                ports:
                - 9814:9814
                volumes:
                        - vici:/var/run
        ipsec:
                build: 
                        dockerfile: Dockerfile.ipsec
                cap_add:
                        - NET_ADMIN
                        - SYS_ADMIN
                sysctls:
                        - net.ipv4.ip_forward=1
                volumes:
                        - vici:/var/run
volumes:
        vici:
